name: django-web

on:  
  push:
      branches:
            - main
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Comprobar repositorio
              uses: actions/checkout@v2

            - name: Configurar Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.13

            - name: Instalar dependencias
              run: |
                  cd ejercicioTrackDevops1-main 
                  pip install -r requirements.txt

            - name: Ejecutar pruebas
              run: |
                    cd ejercicioTrackDevops1-main
                    python manage.py test